### ISSUE TITLE
not work 

### ISSUE THREAD

**Issue by DimonYoing** [Aetheam/SimpleIds_AethTeam#1]
I installed the plugin, the server counted it, but there was no config.yml and the /id command was also not on the server

**Comment by Yoan-Pocketmine** [comment]
hey
It is necessary to put a permission to the players who will have access to the id of the item!
Permission is Use.Ids

**Comment by Yoan-Pocketmine** [comment]
> I installed the plugin, the server counted it, but there was no config.yml and the /id command was also not on the server

hey
It is necessary to put a permission to the players who will have access to the id of the item!
Permission is Use.Ids

**Comment by DimonYoing** [comment]
I'm going to try now

**Comment by royaljacques** [comment]
![image](https://user-images.githubusercontent.com/63215754/152003049-aad79c4f-08f9-4d77-8d5a-7c54767e4c6d.png)
is good no ? 
please dl a new version upload at 1 minutes ago

**Comment by DimonYoing** [comment]
It worked, but can you make it turn on from the /id command?

**Comment by DimonYoing** [comment]
And description in plugin.yml please

**Comment by royaljacques** [comment]
is comming soon

**Comment by Yoan-Pocketmine** [comment]
> It worked, but can you make it turn on from the /id command?


No problem. I am currently working on another project. as soon as this one is finished I will make a version 2 of the plugin or I will add your idea!

**Comment by DimonYoing** [comment]
OK, thanks!

**Comment by DimonYoing** [comment]
I forgot to say that after you enter the command in the chat there was an inscription that the item ID was included, and that the description itself could be changed

**Comment by Yoan-Pocketmine** [comment]
> I forgot to say that after you enter the command in the chat there was an inscription that the item ID was included, and that the description itself could be changed

Okay. do you know the discord of our development team?

**Comment by DimonYoing** [comment]
Not yet, can you explain?

**Comment by DimonYoing** [comment]
If anything, sorry for my translator

**Comment by Yoan-Pocketmine** [comment]
> If anything, sorry for my translator

No problem joining this Discord server:

https://discord.gg/pnSugbKR

**Comment by DimonYoing** [comment]
When can you make a team?

**Comment by DimonYoing** [comment]
command*
